module.exports = [
  {
    jj_prefix: "",
    brand_name: "A",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ACA",
    brand_name: "Accuair",
    vendors: "Meyers, Keystone",
    keystone_code: "ACA",
    meyer_code: "ACA",
  },
  {
    jj_prefix: "ACU",
    brand_name: "AccuPart",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ADD",
    brand_name: "Addictive Desert Designs",
    vendors: "Keystone, Meyers, Quadratec",
    keystone_code: "ADD",
    meyer_code: "ADD",
  },
  {
    jj_prefix: "ADV",
    brand_name: "Advance Adapters",
    vendors: "Meyers, Keystone",
    keystone_code: "A25",
    meyer_code: "AAD",
  },
  {
    jj_prefix: "AEM",
    brand_name: "AEM",
    vendors: "Keystone, Quadratec",
    keystone_code: "A18",
    meyer_code: "",
  },
  {
    jj_prefix: "AFE",
    brand_name: "aFe Power",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "A15",
    meyer_code: "AFE",
  },
  {
    jj_prefix: "AID",
    brand_name: "AIRAID",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "A86",
    meyer_code: "AIR",
  },
  {
    jj_prefix: "ABZ",
    brand_name: "AirBedz",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "ABZ",
    meyer_code: "ABZ",
  },
  {
    jj_prefix: "AIR",
    brand_name: "Air Design",
    vendors: "Keystone, Quadratec",
    keystone_code: "AIR",
    meyer_code: "",
  },
  {
    jj_prefix: "AJT",
    brand_name: "AJT Design",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ALY",
    brand_name: "Alloy USA",
    vendors: "Omix-ADA",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ALP",
    brand_name: "Alpine",
    vendors: "Gentecdirect",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "AEV",
    brand_name: "American Expedition Vehicles (MAP)",
    vendors: "AEV",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "AO",
    brand_name: "American Outlaw",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "AMR",
    brand_name: "American Racing",
    vendors: "Keystone, Quadratec",
    keystone_code: "A78",
    meyer_code: "",
  },
  {
    jj_prefix: "ATP",
    brand_name: "American Trail Products",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "ATP",
  },
  {
    jj_prefix: "AMI",
    brand_name: "AMI Styling",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "AMP",
    brand_name: "AMP Research",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "AMP",
    meyer_code: "AMP",
  },
  {
    jj_prefix: "ANC",
    brand_name: "ANCO",
    vendors: "Keystone",
    keystone_code: "A19",
    meyer_code: "",
  },
  {
    jj_prefix: "ANU",
    brand_name: "ANZO USA",
    vendors: "Meyers, Keystone",
    keystone_code: "A1R",
    meyer_code: "ANZ",
  },
  {
    jj_prefix: "AOC",
    brand_name: "AO Coolers",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "AOC",
  },
  {
    jj_prefix: "ARB",
    brand_name: "ARB",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "ARB",
    meyer_code: "ARB",
  },
  {
    jj_prefix: "ARE",
    brand_name: "A.R.E.",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "ATA",
  },
  {
    jj_prefix: "ARS",
    brand_name: "Aries Automotive",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "A1S",
    meyer_code: "ARI",
  },
  {
    jj_prefix: "AML",
    brand_name: "Armorlite",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "AML",
    meyer_code: "AML",
  },
  {
    jj_prefix: "ARI",
    brand_name: "Artec Industries",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "ACI",
  },
  {
    jj_prefix: "ATG",
    brand_name: "Automotive Gold",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ATW",
    brand_name: "Autowatch Canada",
    vendors: "Autowatch",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ACC",
    brand_name: "Auto Custom Carpets",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ART",
    brand_name: "Auto Rust Technicians",
    vendors: "Auto Rust Technicians",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "AVS",
    brand_name: "Auto Ventshade",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "AVS",
    meyer_code: "AVE",
  },
  {
    jj_prefix: "B",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "BAJ",
    brand_name: "Baja Designs",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B34",
    meyer_code: "BAJ",
  },
  {
    jj_prefix: "BAP",
    brand_name: "Banks Power",
    vendors: "Keystone, Quadratec",
    keystone_code: "B76",
    meyer_code: "",
  },
  {
    jj_prefix: "BDS",
    brand_name: "BDS Suspension",
    vendors: "Grand West",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "BED",
    brand_name: "BedRug",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B63",
    meyer_code: "WIS",
  },
  {
    jj_prefix: "BST",
    brand_name: "BESTOP",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "D34",
    meyer_code: "BES",
  },
  {
    jj_prefix: "BFG",
    brand_name: "BF Goodrich Tires",
    vendors: "Meyers, Tire Discounter",
    keystone_code: "BFG",
    meyer_code: "",
  },
  {
    jj_prefix: "BIL",
    brand_name: "Bilstein",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B52",
    meyer_code: "BIL",
  },
  {
    jj_prefix: "BHO",
    brand_name: "Black Horse Offroad",
    vendors: "Keystone",
    keystone_code: "BLK",
    meyer_code: "",
  },
  {
    jj_prefix: "BLR",
    brand_name: "Black Rhino",
    vendors: "WheelPros",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "BC",
    brand_name: "Black Rock Wheels",
    vendors: "Keystone, Quadratec",
    keystone_code: "BLK",
    meyer_code: "",
  },
  {
    jj_prefix: "BLX",
    brand_name: "Blue Ox",
    vendors: "Meyers, Keystone",
    keystone_code: "B1B",
    meyer_code: "BLU",
  },
  {
    jj_prefix: "BOA",
    brand_name: "Body Armor 4x4",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B96",
    meyer_code: "BOD",
  },
  {
    jj_prefix: "BOL",
    brand_name: "Bolt Lock",
    vendors: "Meyers, Quadratec",
    keystone_code: "S6R",
    meyer_code: "BOL",
  },
  {
    jj_prefix: "BMR",
    brand_name: "Boomerang Enterprises",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "BUC",
    brand_name: "Borgeson",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B73",
    meyer_code: "BUC",
  },
  {
    jj_prefix: "BOR",
    brand_name: "Borla Performance",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B25",
    meyer_code: "BRL",
  },
  {
    jj_prefix: "BRM",
    brand_name: "Brand Motion",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "B1M",
    meyer_code: "BRM",
  },
  {
    jj_prefix: "BRI",
    brand_name: "Briidea",
    vendors: "Amazon",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "BDG",
    brand_name: "Bridgestone",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "BUB",
    brand_name: "Bubba Rope",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "BUB",
  },
  {
    jj_prefix: "BUS",
    brand_name: "BUSHWACKER",
    vendors: "",
    keystone_code: "L22",
    meyer_code: "",
  },
  {
    jj_prefix: "C",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CAM",
    brand_name: "Camco",
    vendors: "Meyers, Keystone",
    keystone_code: "C1W",
    meyer_code: "CMC",
  },
  {
    jj_prefix: "CVR",
    brand_name: "Carnivore",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CAR",
    brand_name: "CARR",
    vendors: "",
    keystone_code: "C22",
    meyer_code: "CAR",
  },
  {
    jj_prefix: "CGG",
    brand_name: "CargoGlide",
    vendors: "Meyers, Keystone",
    keystone_code: "CGL",
    meyer_code: "CGL",
  },
  {
    jj_prefix: "CAT",
    brand_name: "CAT",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CFR",
    brand_name: "Centerforce",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "C78",
    meyer_code: "CTF",
  },
  {
    jj_prefix: "CER",
    brand_name: "Cervini's Auto Design",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CHG",
    brand_name: "Chemical Guys",
    vendors: "Meyers, Keystone",
    keystone_code: "CMG",
    meyer_code: "CHG",
  },
  {
    jj_prefix: "CLZ",
    brand_name: "ClearlidZ",
    vendors: "ClearlidZ",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CLF",
    brand_name: "Cliffride",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "COB",
    brand_name: "Cobra Electronics",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "C98",
    meyer_code: "COB",
  },
  {
    jj_prefix: "COT",
    brand_name: "Cooper Tires",
    vendors: "Canada Tire",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CRB",
    brand_name: "Corbeau",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "CBU",
  },
  {
    jj_prefix: "CRP",
    brand_name: "Corsa Performance",
    vendors: "Keystone, Quadratec",
    keystone_code: "C1M",
    meyer_code: "",
  },
  {
    jj_prefix: "COV",
    brand_name: "Covercraft",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "C59",
    meyer_code: "COV",
  },
  {
    jj_prefix: "CTC",
    brand_name: "Cross Canada",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CRO",
    brand_name: "Crown Automotive",
    vendors: "Crown Directly, Keystone, Meyers, Quadratec",
    keystone_code: "C1Y",
    meyer_code: "CAS",
  },
  {
    jj_prefix: "CRP",
    brand_name: "Crown Performance",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "CUR",
    brand_name: "Currie Enterprises",
    vendors: "Keystone, Quadratec",
    keystone_code: "CEN",
    meyer_code: "",
  },
  {
    jj_prefix: "CMF",
    brand_name: "Curt Manufacturing",
    vendors: "Meyers, Keystone Quadratec",
    keystone_code: "C93",
    meyer_code: "CUR",
  },
  {
    jj_prefix: "D",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "DC",
    brand_name: "D&C Designs",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "DSP",
    brand_name: "Dana Spicer",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "DSP",
    meyer_code: "DNA",
  },
  {
    jj_prefix: "DAY",
    brand_name: "Daystar",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "D78",
    meyer_code: "DAY",
  },
  {
    jj_prefix: "DKD",
    brand_name: "Decked",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "DCK",
    meyer_code: "DCK",
  },
  {
    jj_prefix: "DZE",
    brand_name: "DeeZee",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "DZE",
  },
  {
    jj_prefix: "DOD",
    brand_name: "Diode Dynamics",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "DIO",
    meyer_code: "DDY",
  },
  {
    jj_prefix: "DD",
    brand_name: "Dirty Dog 4X4",
    vendors: "DirtyDog",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "DIT",
    brand_name: "Dirty Life",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "WGH",
    meyer_code: "DLW",
  },
  {
    jj_prefix: "DID",
    brand_name: "Diver Down",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "DOM",
    brand_name: "Dometic",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "D7E",
    meyer_code: "DOM",
  },
  {
    jj_prefix: "DOR",
    brand_name: "Dorman",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "D18",
    meyer_code: "DOR",
  },
  {
    jj_prefix: "DRT",
    brand_name: "Draw-Tite",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "D70",
    meyer_code: "DRT",
  },
  {
    jj_prefix: "DLP",
    brand_name: "Dunlop",
    vendors: "Tire Country",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "DUH",
    brand_name: "DU-HA",
    vendors: "Keystone, Meyers",
    keystone_code: "D67",
    meyer_code: "DUH",
  },
  {
    jj_prefix: "DV8",
    brand_name: "DV8 OffRoad",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "DV8",
    meyer_code: "DVE",
  },
  {
    jj_prefix: "DYN",
    brand_name: "Dynatrac",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "DPC",
  },
  {
    jj_prefix: "DMX",
    brand_name: "DynoMax Exhaust",
    vendors: "Meyers, Keystone",
    keystone_code: "D22",
    meyer_code: "DYN",
  },
  {
    jj_prefix: "E",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "EAT",
    brand_name: "EATON",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "E36",
    meyer_code: "EAT",
  },
  {
    jj_prefix: "EBC",
    brand_name: "EBC Brakes",
    vendors: "Meyers, Keystone",
    keystone_code: "E35",
    meyer_code: "EBC",
  },
  {
    jj_prefix: "EIB",
    brand_name: "Eibach Springs",
    vendors: "Meyers, Keystone",
    keystone_code: "E27",
    meyer_code: "EIB",
  },
  {
    jj_prefix: "ELE",
    brand_name: "Element - Fire Extinguishers",
    vendors: "Meyers, Keystone",
    keystone_code: "EFE",
    meyer_code: "ELE",
  },
  {
    jj_prefix: "ESP",
    brand_name: "Energy Suspension",
    vendors: "Meyers, Keystone",
    keystone_code: "E12",
    meyer_code: "ENG",
  },
  {
    jj_prefix: "EVO",
    brand_name: "EVO Manufacturing",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "EVO",
  },
  {
    jj_prefix: "EXC",
    brand_name: "Excalibur",
    vendors: "Unknown",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "EXR",
    brand_name: "Exposed Racks",
    vendors: "Keystone, Quadratec",
    keystone_code: "EXR",
    meyer_code: "",
  },
  {
    jj_prefix: "EXT",
    brand_name: "Extang",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "E18",
    meyer_code: "EXT",
  },
  {
    jj_prefix: "F",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "FBF",
    brand_name: "Fab Fours",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "F66",
    meyer_code: "FFB",
  },
  {
    jj_prefix: "FBT",
    brand_name: "Fabtech",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "F37",
    meyer_code: "FAB",
  },
  {
    jj_prefix: "F55",
    brand_name: "Factor 55",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "FAC",
    meyer_code: "FCT",
  },
  {
    jj_prefix: "FCI",
    brand_name: "Fairchild Industries",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "FKL",
    brand_name: "Falken WildPeak",
    vendors: "Meyers, Keystone",
    keystone_code: "F34",
    meyer_code: "FTC",
  },
  {
    jj_prefix: "FLK",
    brand_name: "Faulkner",
    vendors: "Keystone",
    keystone_code: "FLK",
    meyer_code: "",
  },
  {
    jj_prefix: "F52",
    brand_name: "Fifteen52",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "FTN",
    brand_name: "Firestone",
    vendors: "Tire Discount",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "FIS",
    brand_name: "Fishbone Offroad",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "FSH",
    meyer_code: "KEN",
  },
  {
    jj_prefix: "FLM",
    brand_name: "FlowMaster",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "F13",
    meyer_code: "FLO",
  },
  {
    jj_prefix: "FOX",
    brand_name: "Fox Racing",
    vendors: "Keystone, Quadratec",
    keystone_code: "F75",
    meyer_code: "",
  },
  {
    jj_prefix: "FRS",
    brand_name: "Free Spirit Recreation",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "FOR",
    brand_name: "Fuel Off-Road",
    vendors: "WheelPros",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "FUA",
    brand_name: "Full Auto",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "G",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "G2",
    brand_name: "G2 Axle & Gear",
    vendors: "Quadratec",
    keystone_code: "G76",
    meyer_code: "GGA",
  },
  {
    jj_prefix: "GSM",
    brand_name: "Garage Smart",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "GRV",
    brand_name: "Garvin Wilderness",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "GRV",
  },
  {
    jj_prefix: "GEN",
    brand_name: "Genright Off Road",
    vendors: "GenRight",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "GBP",
    brand_name: "Gibson Performance",
    vendors: "Keystone, Quadratec",
    keystone_code: "G27",
    meyer_code: "",
  },
  {
    jj_prefix: "GOR",
    brand_name: "Go Rhino",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "G26",
    meyer_code: "RHI",
  },
  {
    jj_prefix: "GYR",
    brand_name: "GOODYEAR",
    vendors: "Tire Country",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "GRA",
    brand_name: "Gorilla Automotive",
    vendors: "Meyers, Keystone",
    keystone_code: "G20",
    meyer_code: "GOL",
  },
  {
    jj_prefix: "",
    brand_name: "Grant Products",
    vendors: "Keystone",
    keystone_code: "G19",
    meyer_code: "",
  },
  {
    jj_prefix: "GRF",
    brand_name: "Griffin Radiator",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "GRL",
    brand_name: "Grote",
    vendors: "Keystone",
    keystone_code: "G17",
    meyer_code: "",
  },
  {
    jj_prefix: "GTS",
    brand_name: "GT Styling",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "G49",
    meyer_code: "GST",
  },
  {
    jj_prefix: "H",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "HAH",
    brand_name: "Harken Hoister",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "HVC",
    brand_name: "Havoc Offroad",
    vendors: "Keystone",
    keystone_code: "O32",
    meyer_code: "",
  },
  {
    jj_prefix: "HEI",
    brand_name: "Heininger Automotive",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "HEI",
  },
  {
    jj_prefix: "HEL",
    brand_name: "HELLA",
    vendors: "Meyers, Keystone",
    keystone_code: "H57",
    meyer_code: "HEL",
  },
  {
    jj_prefix: "HWG",
    brand_name: "Hellwig Suspension",
    vendors: "Meyers, Keystone",
    keystone_code: "H63",
    meyer_code: "HWG",
  },
  {
    jj_prefix: "HIL",
    brand_name: "Hi-Lift Jack",
    vendors: "Meyers, Keystone",
    keystone_code: "H12",
    meyer_code: "HIL",
  },
  {
    jj_prefix: "HOP",
    brand_name: "Hopkins",
    vendors: "Meyers, Keystone",
    keystone_code: "H22",
    meyer_code: "HOP",
  },
  {
    jj_prefix: "HU",
    brand_name: "Husky Liners",
    vendors: "Meyers, Keystone",
    keystone_code: "H21",
    meyer_code: "HSL",
  },
  {
    jj_prefix: "HTP",
    brand_name: "Husky Towing Products",
    vendors: "Keystone",
    keystone_code: "HUS",
    meyer_code: "",
  },
  {
    jj_prefix: "HOR",
    brand_name: "HyLine OffRoad",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "HT",
    brand_name: "Hypertech",
    vendors: "Keystone",
    keystone_code: "H58",
    meyer_code: "",
  },
  {
    jj_prefix: "I",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "IPC",
    brand_name: "In Pro Carwear",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "CAW",
  },
  {
    jj_prefix: "INS",
    brand_name: "INSYNC",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "IRC",
    brand_name: "Iron Cross",
    vendors: "Meyers, Keystone",
    keystone_code: "IRC",
    meyer_code: "IRO",
  },
  {
    jj_prefix: "J",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "JWS",
    brand_name: "J.W. Speaker",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "J47",
    meyer_code: "JWS",
  },
  {
    jj_prefix: "JAM",
    brand_name: "Jammock",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "JBA",
    brand_name: "JBA Performance Exhaust",
    vendors: "Meyers, Keystone Quadratec",
    keystone_code: "J21",
    meyer_code: "JBA",
  },
  {
    jj_prefix: "JEP",
    brand_name: "Jeep",
    vendors: "Quadratec / Elsewhere",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "JTW",
    brand_name: "Jeep Tweaks",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "JET",
    brand_name: "Jet Performance",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "J20",
    meyer_code: "JET",
  },
  {
    jj_prefix: "JKS",
    brand_name: "JKS Manufacturing",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "J46",
    meyer_code: "JKS",
  },
  {
    jj_prefix: "JJ",
    brand_name: "Just Jeeps",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "K",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "K&N",
    brand_name: "K&N",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "K33",
    meyer_code: "KNN",
  },
  {
    jj_prefix: "KCH",
    brand_name: "KC HILITES",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "K13",
    meyer_code: "KCL",
  },
  {
    jj_prefix: "KEN",
    brand_name: "Kentrol",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "KEN",
    meyer_code: "KEN",
  },
  {
    jj_prefix: "KEY",
    brand_name: "KeyParts",
    vendors: "Purchase directly",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "KCR",
    brand_name: "Kicker Jeep Audio & Electronics",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "KIC",
  },
  {
    jj_prefix: "KLN",
    brand_name: "Kleinn",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "K86",
    meyer_code: "KLN",
  },
  {
    jj_prefix: "KMC",
    brand_name: "KMC Wheels",
    vendors: "Wheelpros",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "KRK",
    brand_name: "Krystal Kleer",
    vendors: "Keystone",
    keystone_code: "KAO",
    meyer_code: "",
  },
  {
    jj_prefix: "KMO",
    brand_name: "Kumho",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "L",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "LAO",
    brand_name: "Lange Originals",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "LAN",
  },
  {
    jj_prefix: "LOD",
    brand_name: "LoD Offroad",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "LDB",
  },
  {
    jj_prefix: "LUL",
    brand_name: "Lube Locker",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "LUB",
  },
  {
    jj_prefix: "LUK",
    brand_name: "LUK Clutches",
    vendors: "KING-O-MATIC",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "LUM",
    brand_name: "Lumatron",
    vendors: "Lumatron",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "LYN",
    brand_name: "Lynx",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "M",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MCP",
    brand_name: "MACPEK",
    vendors: "Downsview",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MGF",
    brand_name: "MagnaFlow",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "M66",
    meyer_code: "MAG",
  },
  {
    jj_prefix: "MRS",
    brand_name: "Magnum by Raptor Series",
    vendors: "Keystone, Quadratec",
    keystone_code: "M6B",
    meyer_code: "",
  },
  {
    jj_prefix: "MMO",
    brand_name: "Mamba Offroad",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MST",
    brand_name: "MasterTop",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MAB",
    brand_name: "Max-Bilt",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "MXB",
  },
  {
    jj_prefix: "MXS",
    brand_name: "Maxxis",
    vendors: "Meyers, Keystone Quadratec",
    keystone_code: "M96",
    meyer_code: "MXS",
  },
  {
    jj_prefix: "MAW",
    brand_name: "Mayhem Wheels",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "WGH",
    meyer_code: "MAY",
  },
  {
    jj_prefix: "MBP",
    brand_name: "MBRP Inc",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "M79",
    meyer_code: "MBR",
  },
  {
    jj_prefix: "MCE",
    brand_name: "MCE",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "MCE",
    meyer_code: "MCE",
  },
  {
    jj_prefix: "MCG",
    brand_name: "McGard Wheel Locks",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "M15",
    meyer_code: "MCG",
  },
  {
    jj_prefix: "MDJ",
    brand_name: "MD Juan",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MRW",
    brand_name: "Method Race Wheels",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "MRW",
    meyer_code: "MRW",
  },
  {
    jj_prefix: "MEY",
    brand_name: "Meyer Products",
    vendors: "Meyers, Keystone",
    keystone_code: "M1G",
    meyer_code: "MPR",
  },
  {
    jj_prefix: "MCH",
    brand_name: "Michelin",
    vendors: "Tire Discount",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MKT",
    brand_name: "MICKEY THOMPSON Tires/Wheels",
    vendors: "Meyers, Quadratec",
    keystone_code: "M53, M54, M56",
    meyer_code: "MTT",
  },
  {
    jj_prefix: "MRU",
    brand_name: "Mirage Unlimited",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MSC",
    brand_name: "Misch 4x4",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MIS",
    brand_name: "Mishimoto",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "M1N",
    meyer_code: "MIS",
  },
  {
    jj_prefix: "MON",
    brand_name: "MONROE Shocks & Struts",
    vendors: "Keystone",
    keystone_code: "M45",
    meyer_code: "",
  },
  {
    jj_prefix: "MOO",
    brand_name: "MOOG",
    vendors: "Meyers, Keystone",
    keystone_code: "M12",
    meyer_code: "MOH",
  },
  {
    jj_prefix: "MO",
    brand_name: "MOPAR",
    vendors: "Downsview",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MRY",
    brand_name: "MORryde",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "MRY",
  },
  {
    jj_prefix: "MOG",
    brand_name: "Motive Gear",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "M92",
    meyer_code: "MOG",
  },
  {
    jj_prefix: "MCA",
    brand_name: "Motor City Aftermarket",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "MOR",
    brand_name: "Mountain Offroad",
    vendors: "Quadratec, Keystone",
    keystone_code: "MOR",
    meyer_code: "",
  },
  {
    jj_prefix: "N",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "NFB",
    brand_name: "N-Fab",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "N21",
    meyer_code: "NFB",
  },
  {
    jj_prefix: "NAP",
    brand_name: "Napier Sportz",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "N40",
    meyer_code: "NAE",
  },
  {
    jj_prefix: "NGK",
    brand_name: "NGK",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "N12",
    meyer_code: "NGK",
  },
  {
    jj_prefix: "NIT",
    brand_name: "Nitto Tire",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "NOC",
    brand_name: "NOCO",
    vendors: "Meyers, Keystone",
    keystone_code: "N6C",
    meyer_code: "NOC",
  },
  {
    jj_prefix: "NOV",
    brand_name: "Novak Conversions",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "O",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ODY",
    brand_name: "ODYSSEY Battery",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "O22",
    meyer_code: "ODY",
  },
  {
    jj_prefix: "OOG",
    brand_name: "OFFGRID",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "RSO",
  },
  {
    jj_prefix: "OME",
    brand_name: "Old Man Emu",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "OME",
    meyer_code: "ARB",
  },
  {
    jj_prefix: "OA",
    brand_name: "OMIX-ADA",
    vendors: "Omix-ADA",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "OPT",
    brand_name: "Optima Batteries",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "O10",
    meyer_code: "OPT",
  },
  {
    jj_prefix: "ORL",
    brand_name: "Oracle Lighting",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "O37",
    meyer_code: "ORL",
  },
  {
    jj_prefix: "OBA",
    brand_name: "Outback Adventures",
    vendors: "Northridge 4x4",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "OVO",
    brand_name: "Overland Outfitters",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "OVS",
    brand_name: "Overland Vehicle Systems",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "OVS",
    meyer_code: "UDA",
  },
  {
    jj_prefix: "ORD",
    brand_name: "Overtread",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "P",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "PPP",
    brand_name: "Pacer Performance Products",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P62",
    meyer_code: "PAC",
  },
  {
    jj_prefix: "PAR",
    brand_name: "Paramount Automotive",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P1Z",
    meyer_code: "PMT",
  },
  {
    jj_prefix: "PAV",
    brand_name: "Pavement Ends",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P85",
    meyer_code: "PVT",
  },
  {
    jj_prefix: "PED",
    brand_name: "Pedal Commander",
    vendors: "Keystone, Quadratec",
    keystone_code: "PED",
    meyer_code: "",
  },
  {
    jj_prefix: "PGX",
    brand_name: "Phoenix Graphix",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "PIA",
    brand_name: "PIAA",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P27",
    meyer_code: "PIA",
  },
  {
    jj_prefix: "PAM",
    brand_name: "Pilot Automotive",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P25",
    meyer_code: "WAN",
  },
  {
    jj_prefix: "PLC",
    brand_name: "Plasticolor",
    vendors: "Keystone, Quadratec",
    keystone_code: "P23",
    meyer_code: "",
  },
  {
    jj_prefix: "PS",
    brand_name: "Poison Spyder Customs",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "PSI",
  },
  {
    jj_prefix: "POR",
    brand_name: "POR-15",
    vendors: "Keystone, Quadratec",
    keystone_code: "POR",
    meyer_code: "",
  },
  {
    jj_prefix: "PST",
    brand_name: "Power Stop",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P15",
    meyer_code: "PSB",
  },
  {
    jj_prefix: "PTX",
    brand_name: "Power Trax",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "PTL",
  },
  {
    jj_prefix: "PRP",
    brand_name: "Precision Replacement Parts",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "PRO",
    brand_name: "PRO COMP Alloy Wheels",
    vendors: "Meyers, Keystone",
    keystone_code: "P74",
    meyer_code: "PXA",
  },
  {
    jj_prefix: "PRO",
    brand_name: "PRO COMP Steel Wheels",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "PCW",
  },
  {
    jj_prefix: "PRO",
    brand_name: "PRO COMP Suspension",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "EXP",
  },
  {
    jj_prefix: "PRO",
    brand_name: "PRO COMP Tires",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "PCT",
  },
  {
    jj_prefix: "PRE",
    brand_name: "Pro Eagle",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "PEG",
  },
  {
    jj_prefix: "PRS",
    brand_name: "Pro Series",
    vendors: "Keystone",
    keystone_code: "P2J",
    meyer_code: "",
  },
  {
    jj_prefix: "PMX",
    brand_name: "ProMaxx Automotive",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "PMX",
  },
  {
    jj_prefix: "PSC",
    brand_name: "PSC Steering",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "PSC",
  },
  {
    jj_prefix: "PUT",
    brand_name: "Putco",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "P45",
    meyer_code: "PUT",
  },
  {
    jj_prefix: "Q",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "QTC",
    brand_name: "Quadratec",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "QTC",
    brand_name: "QuadraTop",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "QKE",
    brand_name: "Quake LED",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "QKE",
    meyer_code: "QAK",
  },
  {
    jj_prefix: "R",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RNX",
    brand_name: "RainX",
    vendors: "Meyers, Keystone",
    keystone_code: "R49",
    meyer_code: "ITW",
  },
  {
    jj_prefix: "RPG",
    brand_name: "Rampage Products",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "R92",
    meyer_code: "RAM",
  },
  {
    jj_prefix: "RAN",
    brand_name: "Rancho",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "R38",
    meyer_code: "RHO",
  },
  {
    jj_prefix: "RL",
    brand_name: "ReadyLIFT",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "R90",
    meyer_code: "RDY",
  },
  {
    jj_prefix: "ROR",
    brand_name: "Reaper Off-Road",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "REC",
    brand_name: "Recon",
    vendors: "Meyers, Keystone",
    keystone_code: "R89",
    meyer_code: "REC",
  },
  {
    jj_prefix: "RES",
    brand_name: "RES-Q",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RHI",
    brand_name: "Rhino-Rack",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "RHR",
    meyer_code: "RHR",
  },
  {
    jj_prefix: "RG",
    brand_name: "Rightline Gear",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "RTL",
    meyer_code: "RLG",
  },
  {
    jj_prefix: "RIG",
    brand_name: "Rigid Industries",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "R2G",
    meyer_code: "RIG",
  },
  {
    jj_prefix: "RIP",
    brand_name: "Ripp Supercharger",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RIV",
    brand_name: "Rival 4x4",
    vendors: "Quadratec, Keystone",
    keystone_code: "RVL",
    meyer_code: "",
  },
  {
    jj_prefix: "RAM",
    brand_name: "Road Armor",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "RDA",
    meyer_code: "RDA",
  },
  {
    jj_prefix: "RAC",
    brand_name: "Roam Adventure Co.",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RKJ",
    brand_name: "RockJock",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "CUE",
  },
  {
    jj_prefix: "RKG",
    brand_name: "Rockagator",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "RKG",
  },
  {
    jj_prefix: "RNB",
    brand_name: "RockNob",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RH",
    brand_name: "Rock Hard 4X4",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "RCH",
  },
  {
    jj_prefix: "RK",
    brand_name: "Rock Krawler Suspension",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "RKR",
  },
  {
    jj_prefix: "RSE",
    brand_name: "Rock Slide Engineering",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "RCK",
    meyer_code: "RSE",
  },
  {
    jj_prefix: "RBP",
    brand_name: "Rolling Big Power",
    vendors: "Quadratec, Keystone, Meyers",
    keystone_code: "R94",
    meyer_code: "RBP",
  },
  {
    jj_prefix: "ROM",
    brand_name: "Romik",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "R96",
    meyer_code: "ROM",
  },
  {
    jj_prefix: "ROT",
    brand_name: "RotoPax",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "RTO",
    meyer_code: "RPX",
  },
  {
    jj_prefix: "ROX",
    brand_name: "Rox Offroad",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RC",
    brand_name: "Rough Country",
    vendors: "Rough Country",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RSI",
    brand_name: "RSI",
    vendors: "Keystone",
    keystone_code: "RSI",
    meyer_code: "",
  },
  {
    jj_prefix: "RTO",
    brand_name: "RT Off-Road",
    vendors: "Crown Automotive",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RUB",
    brand_name: "Rubicon Express",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "R97",
    meyer_code: "RUB",
  },
  {
    jj_prefix: "RUR",
    brand_name: "Rugged Radios",
    vendors: "Meyers, Keystone",
    keystone_code: "RGR",
    meyer_code: "RGR",
  },
  {
    jj_prefix: "RR",
    brand_name: "Rugged Ridge",
    vendors: "Omix-ADA",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "RBS",
    brand_name: "Rust Buster",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "RBF",
  },
  {
    jj_prefix: "S",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SNB",
    brand_name: "S&B Filters",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "SNB",
  },
  {
    jj_prefix: "OSS",
    brand_name: "Safety Seal",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SAI",
    brand_name: "Sailun Tires",
    vendors: "Tire Country",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SAV",
    brand_name: "Savvy Off Road",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SSU",
    brand_name: "SeaSucker",
    vendors: "Keystone",
    keystone_code: "SSK",
    meyer_code: "",
  },
  {
    jj_prefix: "SBL",
    brand_name: "Seatbelt Solutions",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SCH",
    brand_name: "Scosche",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "SCO",
    meyer_code: "SCI",
  },
  {
    jj_prefix: "SHM",
    brand_name: "Schumacher",
    vendors: "Keystone",
    keystone_code: "SCH",
    meyer_code: "",
  },
  {
    jj_prefix: "SKY",
    brand_name: "Skyjacker Suspension",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "S97",
    meyer_code: "SKY",
  },
  {
    jj_prefix: "SB",
    brand_name: "Smittybilt",
    vendors: "Meyers, Keystone",
    keystone_code: "S53",
    meyer_code: "SMB",
  },
  {
    jj_prefix: "SFX",
    brand_name: "SpeedFX",
    vendors: "Keystone",
    keystone_code: "S73",
    meyer_code: "",
  },
  {
    jj_prefix: "SPT",
    brand_name: "SpiderTrax",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "S2P",
    meyer_code: "SXO",
  },
  {
    jj_prefix: "SWS",
    brand_name: "SpiderWebShade",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "SWS",
  },
  {
    jj_prefix: "SPB",
    brand_name: "Sprint Booster",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SPA",
    brand_name: "Spyder Automotive",
    vendors: "Meyers, Keystone",
    keystone_code: "S2Z",
    meyer_code: "SPY",
  },
  {
    jj_prefix: "SMA",
    brand_name: "Steer Smarts",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SOR",
    brand_name: "Stinger Off-Road",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "SGR",
  },
  {
    jj_prefix: "SCP",
    brand_name: "Stromberg Carlson Products",
    vendors: "Meyers, Keystone",
    keystone_code: "S21",
    meyer_code: "SCP",
  },
  {
    jj_prefix: "SC",
    brand_name: "Superchips",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "S54",
    meyer_code: "SPC",
  },
  {
    jj_prefix: "SUP",
    brand_name: "Superlift",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "S30",
    meyer_code: "SPL",
  },
  {
    jj_prefix: "SWA",
    brand_name: "Super Swamper",
    vendors: "Meyers, Keystone",
    keystone_code: "S96",
    meyer_code: "ITC",
  },
  {
    jj_prefix: "SUR",
    brand_name: "Surco",
    vendors: "Keystone, Quadratec",
    keystone_code: "S50",
    meyer_code: "",
  },
  {
    jj_prefix: "SWP",
    brand_name: "Switch-Pros",
    vendors: "Switch-Pros",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "SYN",
    brand_name: "Synergy MFG",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "SYN",
  },
  {
    jj_prefix: "T",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "TCK",
    brand_name: "TACTIK",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "TR",
    brand_name: "T-Rex",
    vendors: "Meyers, Keystone",
    keystone_code: "T86",
    meyer_code: "REX",
  },
  {
    jj_prefix: "TEC",
    brand_name: "TecStyle",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "TEK",
    brand_name: "Tekonsha",
    vendors: "Meyers, Keystone",
    keystone_code: "T1M",
    meyer_code: "TEA",
  },
  {
    jj_prefix: "TER",
    brand_name: "TeraFlex",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "TER",
    meyer_code: "TER",
  },
  {
    jj_prefix: "THI",
    brand_name: "THIBERT",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "TH",
    brand_name: "Thule Racks",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "T22",
    meyer_code: "THU",
  },
  {
    jj_prefix: "TIM",
    brand_name: "Timbren",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "T1K",
    meyer_code: "TIM",
  },
  {
    jj_prefix: "TOM",
    brand_name: "Tom Woods",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "TO",
    brand_name: "Toyo Tires",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "T43",
    meyer_code: "TOY",
  },
  {
    jj_prefix: "THC",
    brand_name: "Trail Head Customs",
    vendors: "Trail Head Customs",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "TRA",
    brand_name: "Trail Master",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "TRL",
  },
  {
    jj_prefix: "TFX",
    brand_name: "TrailFX",
    vendors: "Keystone",
    keystone_code: "T82",
    meyer_code: "",
  },
  {
    jj_prefix: "TFS",
    brand_name: "Tuff Stuff 4x4",
    vendors: "Meyers",
    keystone_code: "",
    meyer_code: "TUS",
  },
  {
    jj_prefix: "TY",
    brand_name: "Tuffy Products",
    vendors: "Meyers, Keystone",
    keystone_code: "T60",
    meyer_code: "TFY",
  },
  {
    jj_prefix: "TUX",
    brand_name: "TuxMat",
    vendors: "Tuxmat",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "U",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "UTS",
    brand_name: "Under The Sun",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "UWS",
    brand_name: "UWS Storage",
    vendors: "Meyers, Keystone",
    keystone_code: "U22",
    meyer_code: "UWS",
  },
  {
    jj_prefix: "V",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "VDP",
    brand_name: "Vertically Driven Products",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "V36",
    meyer_code: "VDP",
  },
  {
    jj_prefix: "VSH",
    brand_name: "VersaHitch",
    vendors: "Quadratec",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "VA",
    brand_name: "Viair",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "V6H",
    meyer_code: "VIA",
  },
  {
    jj_prefix: "VVL",
    brand_name: "Vivid Lumen",
    vendors: "Vivid Lumen",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "VX",
    brand_name: "Vision X",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "V47",
    meyer_code: "VIX",
  },
  {
    jj_prefix: "W",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "WAR",
    brand_name: "WARN",
    vendors: "WARN, Meyers, Keystone, Quadratec",
    keystone_code: "W36",
    meyer_code: "WAR",
  },
  {
    jj_prefix: "WA",
    brand_name: "Warrior Products",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "W45",
    meyer_code: "WRR",
  },
  {
    jj_prefix: "WTC",
    brand_name: "WeatherTech",
    vendors: "WeatherTech, Keystone",
    keystone_code: "W2C",
    meyer_code: "",
  },
  {
    jj_prefix: "WES",
    brand_name: "Westin Automotive",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "W16",
    meyer_code: "WES",
  },
  {
    jj_prefix: "WOR",
    brand_name: "Wilco Offroad",
    vendors: "Meyers, Keystone",
    keystone_code: "WLC",
    meyer_code: "WOP",
  },
  {
    jj_prefix: "X",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "XN",
    brand_name: "XENON",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "XEN",
  },
  {
    jj_prefix: "XGC",
    brand_name: "XG Cargo",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "XGC",
    meyer_code: "XGC",
  },
  {
    jj_prefix: "Y",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "DTD",
    brand_name: "YKW",
    vendors: "-",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "YUK",
    brand_name: "Yukon",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "Y11",
    meyer_code: "YUK",
  },
  {
    jj_prefix: "Z",
    brand_name: "",
    vendors: "",
    keystone_code: "",
    meyer_code: "",
  },
  {
    jj_prefix: "ZAM",
    brand_name: "Z Automotive",
    vendors: "Meyers, Quadratec",
    keystone_code: "",
    meyer_code: "ZAT",
  },
  {
    jj_prefix: "ZOR",
    brand_name: "Zone Offroad",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "ZOR",
    meyer_code: "ZOR",
  },
  {
    jj_prefix: "ZRD",
    brand_name: "ZROADZ",
    vendors: "Meyers, Keystone, Quadratec",
    keystone_code: "T86",
    meyer_code: "ZRD",
  },
];
